language: python

python:
  - "2.6"

env:
  - TOXENV=py26-14,py26-15
  - TOXENV=py27-14,py27-15

# command to install dependencies
install:
    - pip install tox

# command to run tests
script:
    - tox
